
# Projet : Reconnaissance d'espèces végétales


# Nom de l'application (doit être en minuscules, sans espaces)
name: plante_app

# Description courte du projet
description: Application reconnaissance plantes

# Version de l'application (1.0.0 = majeure.mineure.patch)
# +1 = numéro de build
version: 1.0.0+1


# ENVIRONNEMENT


environment:
  # Version du SDK Dart requise pour ce projet
  # >=3.0.0 : version minimale
  # <4.0.0 : version maximale (compatible jusqu'à 4.0.0 exclus)
  sdk: ">=3.0.0 <4.0.0"


# DÉPENDANCES (bibliothèques externes utilisées)


dependencies:
  # Framework Flutter (obligatoire)
  flutter:
    sdk: flutter

  # image_picker : permet de sélectionner une image dans la galerie
  # ^0.8.7 : version compatible (>=0.8.7 et <0.9.0)
  image_picker: ^0.8.7

  # tflite_flutter : permet d'exécuter le modèle TensorFlow Lite
  # Utilisé pour la reconnaissance d'images
  tflite_flutter: ^0.10.4

  # image : bibliothèque de traitement d'images
  # Utilisée pour redimensionner et normaliser l'image avant analyse
  image: ^4.1.3


# CONFIGURATION FLUTTER


flutter:
  # Active les icônes Material Design
  uses-material-design: true

  # Liste des fichiers statiques inclus dans l'application
  # Ces fichiers seront embarqués dans l'APK
  assets:
    - assets/model.tflite   # Modèle TensorFlow Lite entraîné
    - assets/labels.txt     # Fichier des noms des 5 espèces de fleurs
